; PlatformIO config that builds the Arduino example for several common boards.
;
; Run from this directory:
;     pio run                       ; build all environments
;     pio run -e uno                ; build only the Uno target
;     pio run -e esp32 -t upload    ; build and flash the ESP32 target

[platformio]
src_dir = ../arduino

[env]
framework = arduino
build_flags = -I${PROJECT_DIR}/../../include
build_src_filter = +<*> +<../../source/tcli.c> +<../../source/tclie.c>
build_unflags = -std=gnu99
build_src_flags = -std=gnu11
monitor_speed = 115200

[env:uno]
platform = atmelavr
board = uno
; Uno has only 2 KB SRAM so we need to disable some features...
build_flags =
    ${env.build_flags}
    -DTCLIE_PATTERN_MATCH=0
    -DTCLIE_ENABLE_USERS=0
    -DTCLI_HISTORY_BUF_LEN=0
    -DTCLI_OUTPUT_BUF_LEN=0
    -DTCLI_CMDLINE_MAX_LEN=32
    -DTCLI_COMPLETE=0

[env:esp32]
platform = espressif32
board = esp32dev

[env:pico]
platform = raspberrypi
board = pico
